# Generated by Django 4.2.1 on 2023-06-16 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizId', models.CharField(default='Aa12345', max_length=7)),
                ('quizTimeStamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.CharField(default='Aa12345', max_length=7)),
                ('questionType', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('FB', 'Fill-in-the-Blank'), ('FMB', 'Fill-in-Multiple-Blanks'), ('MA', 'Multiple Answers'), ('DD', 'Drop-down'), ('MATCH', 'Matching'), ('NUM', 'Numerical Answer'), ('ESSAY', 'Essay'), ('UPLOAD', 'File Upload')], default='MCQ', max_length=30)),
                ('questionText', models.TextField(default='?', help_text='Enter Question')),
                ('questionMarks', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('questionOptions', models.CharField(blank=True, max_length=4000, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAnswer', models.CharField(blank=True, max_length=4000, null=True)),
                ('explaination', models.TextField(blank=True, help_text='Enter Explaination', null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='Quiz.question')),
            ],
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'questionId'), name='unique_question'),
        ),
    ]
