# Generated by Django 4.2.1 on 2023-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizId',
            field=models.CharField(default='Aa12345', max_length=7, unique=True),
        ),
    ]
