# Generated by Django 4.2.1 on 2023-06-07 17:01

import Home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shloka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(default=0)),
                ('shloka', models.PositiveIntegerField(default=0)),
                ('sanskrit', models.ImageField(blank=True, null=True, upload_to=Home.models.Shloka.sanskrit_upload_path)),
                ('hindi', models.ImageField(blank=True, null=True, upload_to=Home.models.Shloka.hindi_upload_path)),
                ('english', models.ImageField(blank=True, null=True, upload_to=Home.models.Shloka.english_upload_path)),
                ('gujarati', models.ImageField(blank=True, null=True, upload_to=Home.models.Shloka.gujarati_upload_path)),
                ('marathi', models.ImageField(blank=True, null=True, upload_to=Home.models.Shloka.marathi_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(default=0)),
                ('shloka', models.PositiveIntegerField(default=0)),
                ('slide_number', models.PositiveIntegerField(default=0)),
                ('slide_image', models.ImageField(blank=True, null=True, upload_to=Home.models.Slide.slides_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(default=0)),
                ('shloka', models.PositiveIntegerField(default=0)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(default=0)),
                ('shloka', models.PositiveIntegerField(default=0)),
                ('video_id', models.CharField(max_length=20)),
                ('video_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='youtubevideos',
            constraint=models.UniqueConstraint(fields=('chapter', 'shloka', 'video_number'), name='unique_video_number'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='slide',
            constraint=models.UniqueConstraint(fields=('chapter', 'shloka', 'slide_number'), name='unique_slide_number'),
        ),
    ]
