# Generated by Django 4.2.1 on 2023-06-04 07:52

import User.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_userprofile_about_alter_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[User.models.UserProfile.only_int, django.core.validators.MinLengthValidator(10)]),
        ),
    ]
