# Generated by Django 4.2.1 on 2023-06-04 08:48

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_userprofile_about_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.UserProfile.profile_pic_path),
        ),
    ]
